name: LocalStack tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: 1.60.0
    - name: Report warnings as errors
      run: echo 'RUSTFLAGS=-D warnings' >> $GITHUB_ENV
    - name: Build
      run: cargo build --locked
    - name: Setup LocalStack
      run: |
        docker run --rm -d --name localstack -p 4566:4566/tcp localstack/localstack
    - name: Run DynamoDB tests
      env:
        AWS_REGION: us-east-1
        AWS_ACCESS_KEY_ID: test
        AWS_SECRET_ACCESS_KEY: test
        LOCALSTACK_ENDPOINT: http://localhost:4566
      run: cargo test --locked -- --ignored dynamo
